// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: worker/v1/worker.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ExecuteStatus represents the status of event execution
type ExecuteStatus int32

const (
	ExecuteStatus_EXECUTE_STATUS_UNSPECIFIED ExecuteStatus = 0
	ExecuteStatus_EXECUTE_STATUS_SUCCESS     ExecuteStatus = 1
	ExecuteStatus_EXECUTE_STATUS_FAILED      ExecuteStatus = 2
	ExecuteStatus_EXECUTE_STATUS_IN_PROGRESS ExecuteStatus = 3
)

// Enum value maps for ExecuteStatus.
var (
	ExecuteStatus_name = map[int32]string{
		0: "EXECUTE_STATUS_UNSPECIFIED",
		1: "EXECUTE_STATUS_SUCCESS",
		2: "EXECUTE_STATUS_FAILED",
		3: "EXECUTE_STATUS_IN_PROGRESS",
	}
	ExecuteStatus_value = map[string]int32{
		"EXECUTE_STATUS_UNSPECIFIED": 0,
		"EXECUTE_STATUS_SUCCESS":     1,
		"EXECUTE_STATUS_FAILED":      2,
		"EXECUTE_STATUS_IN_PROGRESS": 3,
	}
)

func (x ExecuteStatus) Enum() *ExecuteStatus {
	p := new(ExecuteStatus)
	*p = x
	return p
}

func (x ExecuteStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecuteStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_worker_v1_worker_proto_enumTypes[0].Descriptor()
}

func (ExecuteStatus) Type() protoreflect.EnumType {
	return &file_worker_v1_worker_proto_enumTypes[0]
}

func (x ExecuteStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecuteStatus.Descriptor instead.
func (ExecuteStatus) EnumDescriptor() ([]byte, []int) {
	return file_worker_v1_worker_proto_rawDescGZIP(), []int{0}
}

// ExecuteRequest represents a request for executing an event
type ExecuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       int32                  `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Message       []byte                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_worker_v1_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_v1_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_worker_v1_worker_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteRequest) GetEventId() int32 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *ExecuteRequest) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

// ExecuteResponse represents the response from executing an event
type ExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       int32                  `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Message       []byte                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Status        ExecuteStatus          `protobuf:"varint,3,opt,name=status,proto3,enum=flowpilot.worker.v1.ExecuteStatus" json:"status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_worker_v1_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_v1_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_worker_v1_worker_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteResponse) GetEventId() int32 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *ExecuteResponse) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ExecuteResponse) GetStatus() ExecuteStatus {
	if x != nil {
		return x.Status
	}
	return ExecuteStatus_EXECUTE_STATUS_UNSPECIFIED
}

func (x *ExecuteResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// ExecuteAsyncRequest represents a request for asynchronous execution
type ExecuteAsyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       int32                  `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Message       []byte                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	CallbackUrl   string                 `protobuf:"bytes,3,opt,name=callback_url,json=callbackUrl,proto3" json:"callback_url,omitempty"` // Optional callback URL for result notification
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteAsyncRequest) Reset() {
	*x = ExecuteAsyncRequest{}
	mi := &file_worker_v1_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteAsyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteAsyncRequest) ProtoMessage() {}

func (x *ExecuteAsyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_v1_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteAsyncRequest.ProtoReflect.Descriptor instead.
func (*ExecuteAsyncRequest) Descriptor() ([]byte, []int) {
	return file_worker_v1_worker_proto_rawDescGZIP(), []int{2}
}

func (x *ExecuteAsyncRequest) GetEventId() int32 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *ExecuteAsyncRequest) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ExecuteAsyncRequest) GetCallbackUrl() string {
	if x != nil {
		return x.CallbackUrl
	}
	return ""
}

// ExecuteAsyncResponse represents the initial response for async execution
type ExecuteAsyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       int32                  `protobuf:"varint,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Message       []byte                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"` // Echo back the original message
	Status        ExecuteStatus          `protobuf:"varint,4,opt,name=status,proto3,enum=flowpilot.worker.v1.ExecuteStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteAsyncResponse) Reset() {
	*x = ExecuteAsyncResponse{}
	mi := &file_worker_v1_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteAsyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteAsyncResponse) ProtoMessage() {}

func (x *ExecuteAsyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_v1_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteAsyncResponse.ProtoReflect.Descriptor instead.
func (*ExecuteAsyncResponse) Descriptor() ([]byte, []int) {
	return file_worker_v1_worker_proto_rawDescGZIP(), []int{3}
}

func (x *ExecuteAsyncResponse) GetEventId() int32 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *ExecuteAsyncResponse) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ExecuteAsyncResponse) GetStatus() ExecuteStatus {
	if x != nil {
		return x.Status
	}
	return ExecuteStatus_EXECUTE_STATUS_UNSPECIFIED
}

// ExecuteAsyncResult represents the final result of async execution
type ExecuteAsyncResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       int32                  `protobuf:"varint,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Message       []byte                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Status        ExecuteStatus          `protobuf:"varint,4,opt,name=status,proto3,enum=flowpilot.worker.v1.ExecuteStatus" json:"status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteAsyncResult) Reset() {
	*x = ExecuteAsyncResult{}
	mi := &file_worker_v1_worker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteAsyncResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteAsyncResult) ProtoMessage() {}

func (x *ExecuteAsyncResult) ProtoReflect() protoreflect.Message {
	mi := &file_worker_v1_worker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteAsyncResult.ProtoReflect.Descriptor instead.
func (*ExecuteAsyncResult) Descriptor() ([]byte, []int) {
	return file_worker_v1_worker_proto_rawDescGZIP(), []int{4}
}

func (x *ExecuteAsyncResult) GetEventId() int32 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *ExecuteAsyncResult) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ExecuteAsyncResult) GetStatus() ExecuteStatus {
	if x != nil {
		return x.Status
	}
	return ExecuteStatus_EXECUTE_STATUS_UNSPECIFIED
}

func (x *ExecuteAsyncResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_worker_v1_worker_proto protoreflect.FileDescriptor

const file_worker_v1_worker_proto_rawDesc = "" +
	"\n" +
	"\x16worker/v1/worker.proto\x12\x13flowpilot.worker.v1\"E\n" +
	"\x0eExecuteRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\x05R\aeventId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\fR\amessage\"\xa7\x01\n" +
	"\x0fExecuteResponse\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\x05R\aeventId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\fR\amessage\x12:\n" +
	"\x06status\x18\x03 \x01(\x0e2\".flowpilot.worker.v1.ExecuteStatusR\x06status\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"m\n" +
	"\x13ExecuteAsyncRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\x05R\aeventId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\fR\amessage\x12!\n" +
	"\fcallback_url\x18\x03 \x01(\tR\vcallbackUrl\"\x87\x01\n" +
	"\x14ExecuteAsyncResponse\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\x05R\aeventId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\fR\amessage\x12:\n" +
	"\x06status\x18\x04 \x01(\x0e2\".flowpilot.worker.v1.ExecuteStatusR\x06status\"\xaa\x01\n" +
	"\x12ExecuteAsyncResult\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\x05R\aeventId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\fR\amessage\x12:\n" +
	"\x06status\x18\x04 \x01(\x0e2\".flowpilot.worker.v1.ExecuteStatusR\x06status\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage*\x86\x01\n" +
	"\rExecuteStatus\x12\x1e\n" +
	"\x1aEXECUTE_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16EXECUTE_STATUS_SUCCESS\x10\x01\x12\x19\n" +
	"\x15EXECUTE_STATUS_FAILED\x10\x02\x12\x1e\n" +
	"\x1aEXECUTE_STATUS_IN_PROGRESS\x10\x032\x90\x03\n" +
	"\rWorkerService\x12T\n" +
	"\aExecute\x12#.flowpilot.worker.v1.ExecuteRequest\x1a$.flowpilot.worker.v1.ExecuteResponse\x12c\n" +
	"\fExecuteAsync\x12(.flowpilot.worker.v1.ExecuteAsyncRequest\x1a).flowpilot.worker.v1.ExecuteAsyncResponse\x12d\n" +
	"\x0eGetAsyncResult\x12).flowpilot.worker.v1.ExecuteAsyncResponse\x1a'.flowpilot.worker.v1.ExecuteAsyncResult\x12^\n" +
	"\rStreamExecute\x12#.flowpilot.worker.v1.ExecuteRequest\x1a$.flowpilot.worker.v1.ExecuteResponse(\x010\x01B=Z;github.com/flowpilotx/libs/grpc-common/pkg/api/worker/v1;v1b\x06proto3"

var (
	file_worker_v1_worker_proto_rawDescOnce sync.Once
	file_worker_v1_worker_proto_rawDescData []byte
)

func file_worker_v1_worker_proto_rawDescGZIP() []byte {
	file_worker_v1_worker_proto_rawDescOnce.Do(func() {
		file_worker_v1_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_worker_v1_worker_proto_rawDesc), len(file_worker_v1_worker_proto_rawDesc)))
	})
	return file_worker_v1_worker_proto_rawDescData
}

var file_worker_v1_worker_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_worker_v1_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_worker_v1_worker_proto_goTypes = []any{
	(ExecuteStatus)(0),           // 0: flowpilot.worker.v1.ExecuteStatus
	(*ExecuteRequest)(nil),       // 1: flowpilot.worker.v1.ExecuteRequest
	(*ExecuteResponse)(nil),      // 2: flowpilot.worker.v1.ExecuteResponse
	(*ExecuteAsyncRequest)(nil),  // 3: flowpilot.worker.v1.ExecuteAsyncRequest
	(*ExecuteAsyncResponse)(nil), // 4: flowpilot.worker.v1.ExecuteAsyncResponse
	(*ExecuteAsyncResult)(nil),   // 5: flowpilot.worker.v1.ExecuteAsyncResult
}
var file_worker_v1_worker_proto_depIdxs = []int32{
	0, // 0: flowpilot.worker.v1.ExecuteResponse.status:type_name -> flowpilot.worker.v1.ExecuteStatus
	0, // 1: flowpilot.worker.v1.ExecuteAsyncResponse.status:type_name -> flowpilot.worker.v1.ExecuteStatus
	0, // 2: flowpilot.worker.v1.ExecuteAsyncResult.status:type_name -> flowpilot.worker.v1.ExecuteStatus
	1, // 3: flowpilot.worker.v1.WorkerService.Execute:input_type -> flowpilot.worker.v1.ExecuteRequest
	3, // 4: flowpilot.worker.v1.WorkerService.ExecuteAsync:input_type -> flowpilot.worker.v1.ExecuteAsyncRequest
	4, // 5: flowpilot.worker.v1.WorkerService.GetAsyncResult:input_type -> flowpilot.worker.v1.ExecuteAsyncResponse
	1, // 6: flowpilot.worker.v1.WorkerService.StreamExecute:input_type -> flowpilot.worker.v1.ExecuteRequest
	2, // 7: flowpilot.worker.v1.WorkerService.Execute:output_type -> flowpilot.worker.v1.ExecuteResponse
	4, // 8: flowpilot.worker.v1.WorkerService.ExecuteAsync:output_type -> flowpilot.worker.v1.ExecuteAsyncResponse
	5, // 9: flowpilot.worker.v1.WorkerService.GetAsyncResult:output_type -> flowpilot.worker.v1.ExecuteAsyncResult
	2, // 10: flowpilot.worker.v1.WorkerService.StreamExecute:output_type -> flowpilot.worker.v1.ExecuteResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_worker_v1_worker_proto_init() }
func file_worker_v1_worker_proto_init() {
	if File_worker_v1_worker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_worker_v1_worker_proto_rawDesc), len(file_worker_v1_worker_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_worker_v1_worker_proto_goTypes,
		DependencyIndexes: file_worker_v1_worker_proto_depIdxs,
		EnumInfos:         file_worker_v1_worker_proto_enumTypes,
		MessageInfos:      file_worker_v1_worker_proto_msgTypes,
	}.Build()
	File_worker_v1_worker_proto = out.File
	file_worker_v1_worker_proto_goTypes = nil
	file_worker_v1_worker_proto_depIdxs = nil
}
