apiVersion: v1
kind: Service
metadata:
  name: nats-jetstream
spec:
  type: NodePort
  selector:
    app: nats-jetstream
  ports:
    - name: client
      port: 4222
      targetPort: 4222
      nodePort: 30422
    - name: cluster
      port: 6222
      targetPort: 6222
      nodePort: 30622
    - name: monitoring
      port: 8222
      targetPort: 8222
      nodePort: 30822 