apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nats-jetstream
spec:
  serviceName: "nats-jetstream"
  replicas: 1
  selector:
    matchLabels:
      app: nats-jetstream
  template:
    metadata:
      labels:
        app: nats-jetstream
    spec:
      containers:
        - name: nats
          image: nats:latest
          command: [ "nats-server", "-js" ]
          ports:
            - containerPort: 4222
            - containerPort: 6222
            - containerPort: 8222
          volumeMounts:
            - name: nats-data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: nats-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi
