apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-wf-cache
spec:
  serviceName: "redis-wf-cache"
  replicas: 1
  selector:
    matchLabels:
      app: redis-wf-cache
  template:
    metadata:
      labels:
        app: redis-wf-cache
    spec:
      containers:
        - name: redis-wf-cache
          image: redis:latest
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-wf-cache-data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: redis-wf-cache-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
