/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'canvas': {
          DEFAULT: '#FFFFFF',
          dark: '#1E1E1E',
          miro: '#FFFFFF',
        },
        'sidebar': {
          DEFAULT: '#FFFFFF',
          dark: '#252526',
          hover: '#F5F5F5',
          'hover-dark': '#2D2D2D',
        },
        'node': {
          'bg': '#FFFFFF',
          'bg-dark': '#2A2A2A',
          'border': '#E5E5E5',
          'border-dark': '#404040',
          'header': {
            'add': '#00A3BF',
            'multiply': '#FF6B6B',
          },
          'vscode': {
            'bg': '#252526',
            'border': '#454545',
            'selected': '#094771',
            'hover': '#2D2D2D',
            'text': '#CCCCCC',
            'add': '#4EC9B0',
            'multiply': '#CE9178',
            'handle': '#569CD6',
            'input': {
              'bg': '#3C3C3C',
              'border': '#454545',
              'focus-border': '#007ACC',
              'hover-border': '#565656',
              'placeholder': '#808080',
            },
            'button': '#37373D',
            'button-hover': '#2D2D2D',
          },
          'miro': {
            'bg': '#FFFFFF',
            'border': '#E0E0E0',
            'selected': '#2D9CDB',
            'hover': '#F8F9FA',
            'text': '#333333',
            'add': '#4573D5',
            'multiply': '#FF7262',
            'handle': '#2D9CDB',
            'input': {
              'bg': '#F5F5F5',
              'border': '#E0E0E0',
              'focus-border': '#2D9CDB',
              'hover-border': '#CCCCCC',
              'placeholder': '#999999',
            },
            'button': '#F5F5F5',
            'button-hover': '#EAEAEA',
          },
        },
        'accent': {
          primary: '#2563EB',
          success: '#10B981',
          warning: '#F59E0B',
          danger: '#EF4444',
        },
        'accent-primary': '#2563EB',
        'accent-primary-dark': '#2563EB',
        'node-vscode-bg': '#2D2D2D',
        'node-vscode-border': '#404040',
        'node-vscode-text': '#D4D4D4',
        'node-vscode-selected': '#264F78',
        'node-vscode-add': '#9B51E0',
        'node-vscode-multiply': '#F2994A',
        'node-miro-bg': '#FFFFFF',
        'node-miro-border': '#E6E6E6',
        'node-miro-text': '#333333',
        'node-miro-selected': '#2563EB',
        'node-miro-add': '#6366F1',
        'node-miro-multiply': '#F59E0B',
      },
      width: {
        'sidebar': '280px',
        'sidebar-collapsed': '50px',
      },
      boxShadow: {
        'node': '0 2px 4px rgba(0, 0, 0, 0.1)',
        'node-dark': '0 2px 4px rgba(0, 0, 0, 0.2)',
        'sidebar': '1px 0 0 0 rgba(0, 0, 0, 0.1)',
        'sidebar-dark': '1px 0 0 0 rgba(255, 255, 255, 0.1)',
        'node-vscode': '0 2px 8px rgba(0, 0, 0, 0.3)',
        'node-miro': '0 2px 4px rgba(0, 0, 0, 0.1)',
        'node-selected-vscode': '0 0 0 2px #094771',
        'node-selected-miro': '0 0 0 2px #2D9CDB',
        'input-vscode': '0 0 0 1px #454545',
        'input-vscode-focus': '0 0 0 1px #007ACC',
        'input-miro': '0 0 0 1px #E0E0E0',
        'input-miro-focus': '0 0 0 1px #2D9CDB',
      },
      keyframes: {
        'fade-in': {
          '0%': { opacity: '0', transform: 'translateY(-10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'node-hover': {
          '0%': { transform: 'scale(1)' },
          '100%': { transform: 'scale(1.02)' },
        },
      },
      animation: {
        'fade-in': 'fade-in 0.2s ease-in-out forwards',
        'node-hover': 'node-hover 0.15s ease-in-out forwards',
      }
    },
  },
  plugins: [],
} 